### ISSUE TITLE
建议做一个写入的例子

### ISSUE THREAD

**Issue by wchcom** [zhanghai/libarchive-android#1]
你好，看了贵哥提供的SDK很强大，但是没有压缩的例子，建议出一个压缩的例子，你做的文件管理器里太复杂了小弟看不懂

**Comment by zhanghai** [comment]
看这个就行了：https://github.com/zhanghai/MaterialFiles/blob/master/app/src/main/java/me/zhanghai/android/files/provider/archive/archiver/ArchiveWriter.kt

**Comment by wchcom** [comment]
之前也看了，也很难，可以通过File写一个简单的demo吗
